# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from bee_rpc import buffer_pb2 as buffer__pb2


class GatewayStub(object):
    """-----------------------
    GATEWAY SERVICE DEFINITION
    -----------------------

    The Gateway of a node. Each RPC is a stream of buffer.Buffer in each direction. The
    celaut-gateway layer of each address gives the message type at each bee-rpc index and
    the kind of authentication of each RPC:
    * client: a Client in the request, at the index that the layer gives, in any
    sequence. A local instance of the node is exempt. All these RPCs share one rate
    limit for each client_id.
    * token: a token in the payload (an instance token; GetMetrics also takes a
    client_id).
    * client-in-message: Chat, with the client_id in the ChatMessage.
    * local-address: ModifyServiceSystemResources, only for a local instance.
    * none: GenerateClient, which can answer with a PoWRequired.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartService = channel.stream_stream(
                '/celaut.Gateway/StartService',
                request_serializer=buffer__pb2.Buffer.SerializeToString,
                response_deserializer=buffer__pb2.Buffer.FromString,
                )
        self.StopService = channel.stream_stream(
                '/celaut.Gateway/StopService',
                request_serializer=buffer__pb2.Buffer.SerializeToString,
                response_deserializer=buffer__pb2.Buffer.FromString,
                )
        self.ModifyDeposit = channel.stream_stream(
                '/celaut.Gateway/ModifyDeposit',
                request_serializer=buffer__pb2.Buffer.SerializeToString,
                response_deserializer=buffer__pb2.Buffer.FromString,
                )
        self.GetPeerInfo = channel.stream_stream(
                '/celaut.Gateway/GetPeerInfo',
                request_serializer=buffer__pb2.Buffer.SerializeToString,
                response_deserializer=buffer__pb2.Buffer.FromString,
                )
        self.ResolveNetwork = channel.stream_stream(
                '/celaut.Gateway/ResolveNetwork',
                request_serializer=buffer__pb2.Buffer.SerializeToString,
                response_deserializer=buffer__pb2.Buffer.FromString,
                )
        self.IntroducePeer = channel.stream_stream(
                '/celaut.Gateway/IntroducePeer',
                request_serializer=buffer__pb2.Buffer.SerializeToString,
                response_deserializer=buffer__pb2.Buffer.FromString,
                )
        self.GenerateClient = channel.stream_stream(
                '/celaut.Gateway/GenerateClient',
                request_serializer=buffer__pb2.Buffer.SerializeToString,
                response_deserializer=buffer__pb2.Buffer.FromString,
                )
        self.AssociateClient = channel.stream_stream(
                '/celaut.Gateway/AssociateClient',
                request_serializer=buffer__pb2.Buffer.SerializeToString,
                response_deserializer=buffer__pb2.Buffer.FromString,
                )
        self.GenerateDepositToken = channel.stream_stream(
                '/celaut.Gateway/GenerateDepositToken',
                request_serializer=buffer__pb2.Buffer.SerializeToString,
                response_deserializer=buffer__pb2.Buffer.FromString,
                )
        self.Payable = channel.stream_stream(
                '/celaut.Gateway/Payable',
                request_serializer=buffer__pb2.Buffer.SerializeToString,
                response_deserializer=buffer__pb2.Buffer.FromString,
                )
        self.ModifyServiceSystemResources = channel.stream_stream(
                '/celaut.Gateway/ModifyServiceSystemResources',
                request_serializer=buffer__pb2.Buffer.SerializeToString,
                response_deserializer=buffer__pb2.Buffer.FromString,
                )
        self.GetServiceEstimatedCost = channel.stream_stream(
                '/celaut.Gateway/GetServiceEstimatedCost',
                request_serializer=buffer__pb2.Buffer.SerializeToString,
                response_deserializer=buffer__pb2.Buffer.FromString,
                )
        self.GetResourceAvailability = channel.stream_stream(
                '/celaut.Gateway/GetResourceAvailability',
                request_serializer=buffer__pb2.Buffer.SerializeToString,
                response_deserializer=buffer__pb2.Buffer.FromString,
                )
        self.GetService = channel.stream_stream(
                '/celaut.Gateway/GetService',
                request_serializer=buffer__pb2.Buffer.SerializeToString,
                response_deserializer=buffer__pb2.Buffer.FromString,
                )
        self.GetMetrics = channel.stream_stream(
                '/celaut.Gateway/GetMetrics',
                request_serializer=buffer__pb2.Buffer.SerializeToString,
                response_deserializer=buffer__pb2.Buffer.FromString,
                )
        self.ServiceTunnel = channel.stream_stream(
                '/celaut.Gateway/ServiceTunnel',
                request_serializer=buffer__pb2.Buffer.SerializeToString,
                response_deserializer=buffer__pb2.Buffer.FromString,
                )
        self.Observe = channel.stream_stream(
                '/celaut.Gateway/Observe',
                request_serializer=buffer__pb2.Buffer.SerializeToString,
                response_deserializer=buffer__pb2.Buffer.FromString,
                )
        self.Chat = channel.stream_stream(
                '/celaut.Gateway/Chat',
                request_serializer=buffer__pb2.Buffer.SerializeToString,
                response_deserializer=buffer__pb2.Buffer.FromString,
                )


class GatewayServicer(object):
    """-----------------------
    GATEWAY SERVICE DEFINITION
    -----------------------

    The Gateway of a node. Each RPC is a stream of buffer.Buffer in each direction. The
    celaut-gateway layer of each address gives the message type at each bee-rpc index and
    the kind of authentication of each RPC:
    * client: a Client in the request, at the index that the layer gives, in any
    sequence. A local instance of the node is exempt. All these RPCs share one rate
    limit for each client_id.
    * token: a token in the payload (an instance token; GetMetrics also takes a
    client_id).
    * client-in-message: Chat, with the client_id in the ChatMessage.
    * local-address: ModifyServiceSystemResources, only for a local instance.
    * none: GenerateClient, which can answer with a PoWRequired.
    """

    def StartService(self, request_iterator, context):
        """Starts a service. The caller sends a Client and the service as content hashes, as
        Metadata or as the full Service. It can also send a Configuration and a
        RecursionGuard. The node returns a ServiceInstance with the addresses of the
        instance and its token. The node can start the service on a peer and give the
        addresses of that instance. If the node does not have the service and the caller
        does not send it, the node refuses with an error.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopService(self, request_iterator, context):
        """Stops an instance. The TokenMessage gives the instance token. The node gives the
        balance that the instance did not use back to its parent, and returns a Refund
        with that amount. If the node does not know the token, the Refund is 0.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyDeposit(self, request_iterator, context):
        """Changes the balance of an instance. The service_token gives the instance. The
        parent of the instance pays or gets the difference.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeerInfo(self, request_iterator, context):
        """Returns the Peer of the node. The Peer gives all the addresses of the node, the
        payment contracts, the rates and the reputation proofs. The signature of the
        Peer covers all of these.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveNetwork(self, request_iterator, context):
        """Any Service.Network, not one kind of it. If the caller must know the kind first,
        the caller does the resolution itself. A `pow:` network has no name to look up,
        so the node must find its addresses (issue #78).

        Takes a Service.Network and returns the addresses of the members of that network
        that the node can find. The node does not ask other nodes. This is what the node
        believes, not a proof: the caller must make sure that each address is correct.
        The node refuses a network that its policy does not allow, and a network with an
        unfilled ${VAR}. For a local instance, the request must agree with a network that
        its service declares. The node then also opens the addresses in the firewall of
        that instance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IntroducePeer(self, request_iterator, context):
        """Sends the Peer of the caller, with a Client. The node returns a RecursionGuard.
        Its token is the peer id (the public key) of the caller if the node knows the
        caller now, or "REFUSED".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateClient(self, request_iterator, context):
        """Returns a new Client. The caller can send a Client with a proposed client_id. It
        can also send a peer_id and a signature to bind the client to that peer. The node
        binds it only if it already knows that peer. If not, use AssociateClient later.
        If the node needs a proof of work, it returns a PoWRequired at index 2. Then the
        caller sends the Client again, with the same client_id, the challenge and a
        solution.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssociateClient(self, request_iterator, context):
        """Binds a client_id to the identity of the caller, after IntroducePeer stored the
        caller as a peer. The Client gives the client_id, the peer_id and a signature.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateDepositToken(self, request_iterator, context):
        """Returns a TokenMessage with a new deposit token for the client. The payer writes
        this token in its ledger transaction. The payment contract gives where and how.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Payable(self, request_iterator, context):
        """Tells the node about a payment. The Payment gives the deposit token, the contract
        and the amount. The node examines the ledger. Then it adds the amount to the
        client that got that deposit token. The node accepts each deposit token one time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyServiceSystemResources(self, request_iterator, context):
        """Changes the resource limits of an instance. Only a local instance of the node can
        call it. The node identifies the instance by its address. The node takes a fee
        from the balance of the instance. It returns the new resources and the balance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceEstimatedCost(self, request_iterator, context):
        """Takes the same objects as StartService. Returns the cost to run the service on
        this node, and starts nothing. A node that cannot run the service now refuses
        with the reason. If the node does not have the service and the caller does not
        send it, the node refuses with an error. The node ignores a RecursionGuard here.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResourceAvailability(self, request_iterator, context):
        """Asks if the node can run one instance with the given architecture and resources
        now. The resources do not need to be those of a known service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetService(self, request_iterator, context):
        """Takes a content hash. Returns the hashes at index 4, the Metadata at index 5 and
        the Service at index 6. These are the StartService indices, so the caller can send
        them to StartService without a change.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request_iterator, context):
        """Takes a token. For an instance token, returns the balance of the instance. For a
        client_id, returns the balance of the client.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServiceTunnel(self, request_iterator, context):
        """Opens a byte stream to a declared slot of a local instance. First, the caller
        sends a TokenMessage with the instance token and the internal port in slot. Then
        each side sends raw bytes at index 0. For a TCP slot, when the stream of the
        caller stops, the node closes the write side of the connection to the service.
        For a UDP slot, each message is one datagram. The node takes the traffic cost
        from the balance of the instance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Observe(self, request_iterator, context):
        """Takes an ObserveRequest and returns a stream of ObserveEvent. If the observation
        starts, the first event is a session event. If not, the stream has only one
        notice that tells why. The stream stops when the instance stops.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request_iterator, context):
        """Sends a ChatMessage to the operator of the node. The node returns a ChatAck.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartService': grpc.stream_stream_rpc_method_handler(
                    servicer.StartService,
                    request_deserializer=buffer__pb2.Buffer.FromString,
                    response_serializer=buffer__pb2.Buffer.SerializeToString,
            ),
            'StopService': grpc.stream_stream_rpc_method_handler(
                    servicer.StopService,
                    request_deserializer=buffer__pb2.Buffer.FromString,
                    response_serializer=buffer__pb2.Buffer.SerializeToString,
            ),
            'ModifyDeposit': grpc.stream_stream_rpc_method_handler(
                    servicer.ModifyDeposit,
                    request_deserializer=buffer__pb2.Buffer.FromString,
                    response_serializer=buffer__pb2.Buffer.SerializeToString,
            ),
            'GetPeerInfo': grpc.stream_stream_rpc_method_handler(
                    servicer.GetPeerInfo,
                    request_deserializer=buffer__pb2.Buffer.FromString,
                    response_serializer=buffer__pb2.Buffer.SerializeToString,
            ),
            'ResolveNetwork': grpc.stream_stream_rpc_method_handler(
                    servicer.ResolveNetwork,
                    request_deserializer=buffer__pb2.Buffer.FromString,
                    response_serializer=buffer__pb2.Buffer.SerializeToString,
            ),
            'IntroducePeer': grpc.stream_stream_rpc_method_handler(
                    servicer.IntroducePeer,
                    request_deserializer=buffer__pb2.Buffer.FromString,
                    response_serializer=buffer__pb2.Buffer.SerializeToString,
            ),
            'GenerateClient': grpc.stream_stream_rpc_method_handler(
                    servicer.GenerateClient,
                    request_deserializer=buffer__pb2.Buffer.FromString,
                    response_serializer=buffer__pb2.Buffer.SerializeToString,
            ),
            'AssociateClient': grpc.stream_stream_rpc_method_handler(
                    servicer.AssociateClient,
                    request_deserializer=buffer__pb2.Buffer.FromString,
                    response_serializer=buffer__pb2.Buffer.SerializeToString,
            ),
            'GenerateDepositToken': grpc.stream_stream_rpc_method_handler(
                    servicer.GenerateDepositToken,
                    request_deserializer=buffer__pb2.Buffer.FromString,
                    response_serializer=buffer__pb2.Buffer.SerializeToString,
            ),
            'Payable': grpc.stream_stream_rpc_method_handler(
                    servicer.Payable,
                    request_deserializer=buffer__pb2.Buffer.FromString,
                    response_serializer=buffer__pb2.Buffer.SerializeToString,
            ),
            'ModifyServiceSystemResources': grpc.stream_stream_rpc_method_handler(
                    servicer.ModifyServiceSystemResources,
                    request_deserializer=buffer__pb2.Buffer.FromString,
                    response_serializer=buffer__pb2.Buffer.SerializeToString,
            ),
            'GetServiceEstimatedCost': grpc.stream_stream_rpc_method_handler(
                    servicer.GetServiceEstimatedCost,
                    request_deserializer=buffer__pb2.Buffer.FromString,
                    response_serializer=buffer__pb2.Buffer.SerializeToString,
            ),
            'GetResourceAvailability': grpc.stream_stream_rpc_method_handler(
                    servicer.GetResourceAvailability,
                    request_deserializer=buffer__pb2.Buffer.FromString,
                    response_serializer=buffer__pb2.Buffer.SerializeToString,
            ),
            'GetService': grpc.stream_stream_rpc_method_handler(
                    servicer.GetService,
                    request_deserializer=buffer__pb2.Buffer.FromString,
                    response_serializer=buffer__pb2.Buffer.SerializeToString,
            ),
            'GetMetrics': grpc.stream_stream_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=buffer__pb2.Buffer.FromString,
                    response_serializer=buffer__pb2.Buffer.SerializeToString,
            ),
            'ServiceTunnel': grpc.stream_stream_rpc_method_handler(
                    servicer.ServiceTunnel,
                    request_deserializer=buffer__pb2.Buffer.FromString,
                    response_serializer=buffer__pb2.Buffer.SerializeToString,
            ),
            'Observe': grpc.stream_stream_rpc_method_handler(
                    servicer.Observe,
                    request_deserializer=buffer__pb2.Buffer.FromString,
                    response_serializer=buffer__pb2.Buffer.SerializeToString,
            ),
            'Chat': grpc.stream_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=buffer__pb2.Buffer.FromString,
                    response_serializer=buffer__pb2.Buffer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'celaut.Gateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Gateway(object):
    """-----------------------
    GATEWAY SERVICE DEFINITION
    -----------------------

    The Gateway of a node. Each RPC is a stream of buffer.Buffer in each direction. The
    celaut-gateway layer of each address gives the message type at each bee-rpc index and
    the kind of authentication of each RPC:
    * client: a Client in the request, at the index that the layer gives, in any
    sequence. A local instance of the node is exempt. All these RPCs share one rate
    limit for each client_id.
    * token: a token in the payload (an instance token; GetMetrics also takes a
    client_id).
    * client-in-message: Chat, with the client_id in the ChatMessage.
    * local-address: ModifyServiceSystemResources, only for a local instance.
    * none: GenerateClient, which can answer with a PoWRequired.
    """

    @staticmethod
    def StartService(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/celaut.Gateway/StartService',
            buffer__pb2.Buffer.SerializeToString,
            buffer__pb2.Buffer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopService(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/celaut.Gateway/StopService',
            buffer__pb2.Buffer.SerializeToString,
            buffer__pb2.Buffer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ModifyDeposit(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/celaut.Gateway/ModifyDeposit',
            buffer__pb2.Buffer.SerializeToString,
            buffer__pb2.Buffer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPeerInfo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/celaut.Gateway/GetPeerInfo',
            buffer__pb2.Buffer.SerializeToString,
            buffer__pb2.Buffer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResolveNetwork(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/celaut.Gateway/ResolveNetwork',
            buffer__pb2.Buffer.SerializeToString,
            buffer__pb2.Buffer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IntroducePeer(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/celaut.Gateway/IntroducePeer',
            buffer__pb2.Buffer.SerializeToString,
            buffer__pb2.Buffer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateClient(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/celaut.Gateway/GenerateClient',
            buffer__pb2.Buffer.SerializeToString,
            buffer__pb2.Buffer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AssociateClient(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/celaut.Gateway/AssociateClient',
            buffer__pb2.Buffer.SerializeToString,
            buffer__pb2.Buffer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateDepositToken(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/celaut.Gateway/GenerateDepositToken',
            buffer__pb2.Buffer.SerializeToString,
            buffer__pb2.Buffer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Payable(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/celaut.Gateway/Payable',
            buffer__pb2.Buffer.SerializeToString,
            buffer__pb2.Buffer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ModifyServiceSystemResources(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/celaut.Gateway/ModifyServiceSystemResources',
            buffer__pb2.Buffer.SerializeToString,
            buffer__pb2.Buffer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServiceEstimatedCost(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/celaut.Gateway/GetServiceEstimatedCost',
            buffer__pb2.Buffer.SerializeToString,
            buffer__pb2.Buffer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetResourceAvailability(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/celaut.Gateway/GetResourceAvailability',
            buffer__pb2.Buffer.SerializeToString,
            buffer__pb2.Buffer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetService(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/celaut.Gateway/GetService',
            buffer__pb2.Buffer.SerializeToString,
            buffer__pb2.Buffer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMetrics(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/celaut.Gateway/GetMetrics',
            buffer__pb2.Buffer.SerializeToString,
            buffer__pb2.Buffer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServiceTunnel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/celaut.Gateway/ServiceTunnel',
            buffer__pb2.Buffer.SerializeToString,
            buffer__pb2.Buffer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Observe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/celaut.Gateway/Observe',
            buffer__pb2.Buffer.SerializeToString,
            buffer__pb2.Buffer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Chat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/celaut.Gateway/Chat',
            buffer__pb2.Buffer.SerializeToString,
            buffer__pb2.Buffer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
